---
- name: "Install packages"
  ansible.builtin.package:
    update_cache: false
    name:
      - "apt-transport-https"

- name: "Install Kibana"
  notify: 
    - "Enable and start Kibana"
  block:
    - name: "Add Kibana GPG apt Key"
      ansible.builtin.apt_key:
        url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"

    - name: "Add Kibana Repository"
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://artifacts.elastic.co/packages/{{ install_kibana_major_version }}.x/apt stable main"

    - name: "Update apt and install Kibana"
      ansible.builtin.apt:
        update_cache: false
        name:
          - "kibana"

- name: "Configure Kibana"
  notify:
    - "Restart Kibana"
    - "Delay Kibana starting"
  block:
    - name: "Get new enrollment TOKEN"
      run_once: true
      when: not (install_kibana_service_account_token_fact | default(false))
      block:
        - name: "Get the token client certs"
          when:  install_kibana_elastic_client_auth | default(false)
          block:
            - name: "Call the API and get a new TOKEN CERT"
              register: install_kibana_service_account_token_response
              failed_when: install_kibana_service_account_token_response.json.created != true
              changed_when: install_kibana_service_account_token_response.json.created != true
              ansible.builtin.uri:
                url: "{{ install_kibana_elastic_protocol }}://{{ inventory_hostname }}:{{ install_kibana_elasticsearch_port }}/_security/service/elastic/kibana/credential/token/service_account_token-kibana-{{ install_kibana_service_account_token_basename }}?pretty=true"
                method: POST
                user: "elastic"
                password: "{{ install_kibana_elastic_password }}"
                client_cert: "{{ install_kibana_ssl_crt }}"
                client_key: "{{ install_kibana_ssl_key }}"

            - name: "Get/Set enrollment fact TOKEN"
              ansible.builtin.set_fact:
                cacheable: true
                install_kibana_service_account_token_fact: "{{ install_kibana_service_account_token_response.json.token.value }}"
                install_kibana_service_account_token: "{{ install_kibana_service_account_token_response.json.token.value }}"

        - name: "Get the token without client certs"
          when: not (install_kibana_elastic_client_auth | default(true))
          block:
            - name: "Call the API and get a new TOKEN"
              register: install_kibana_service_account_token_response
              failed_when: install_kibana_service_account_token_response.json.created != true
              changed_when: install_kibana_service_account_token_response.json.created != true
              ansible.builtin.uri:
                url: "{{ install_kibana_elastic_protocol }}://{{ inventory_hostname }}:{{ install_kibana_elasticsearch_port }}/_security/service/elastic/kibana/credential/token/service_account_token-kibana-{{ install_kibana_service_account_token_basename }}?pretty=true"
                method: POST
                user: "elastic"
                password: "{{ install_kibana_elastic_password }}"

            - name: "Get/Set enrollment fact TOKEN"
              ansible.builtin.set_fact:
                cacheable: true
                install_kibana_service_account_token_fact: "{{ install_kibana_service_account_token_response.json.token.value }}"
                install_kibana_service_account_token: "{{ install_kibana_service_account_token_response.json.token.value }}"

    - name: "Import Kibana configuration file"
      ansible.builtin.template:
        src: "templates/kibana.yml.j2"
        dest: "{{ install_kibana_config_path }}/kibana.yml"
        mode: "0660"
        group: "{{ install_kibana_group }}"
        owner: "root"
        lstrip_blocks: yes
