---
- name: "Converge"
  hosts: "cicd-debian-12"
  tasks:

    - name: "Include labocbz.install_kibana"
      tags:
        - "labocbz.install_kibana"
      vars:
        install_kibana__major_version: "{{ inv_install_kibana__major_version }}"
        install_kibana__config_path: "{{ inv_install_kibana__config_path }}"
        install_kibana__port: "{{ inv_install_kibana__port }}"
        install_kibana__cluster_name: "{{ inv_install_kibana__cluster_name }}"
        install_kibana__rewrite_base_path: "{{ inv_install_kibana__rewrite_base_path }}"
        install_kibana__base_path: "{{ inv_install_kibana__base_path }}"
        install_kibana__public_pase_url: "{{ inv_install_kibana__public_pase_url }}"
        install_kibana__ssl: "{{ inv_install_kibana__ssl }}"
        install_kibana__ssl_path: "{{ inv_install_kibana__ssl_path }}"
        install_kibana__elasticsearch_port: "{{ inv_install_kibana__elasticsearch_port }}"
        #install_kibana__service_account_token: "{{ inv_install_kibana__service_account_token }}"
        install_kibana__service_account_token_basename: "{{ inv_install_kibana__service_account_token_basename }}"
        install_kibana__elastic_password: "{{ inv_install_kibana__elastic_password }}"
        install_kibana__elastic_user: "{{ inv_install_kibana__elastic_user }}"
        install_kibana__elastic_protocol: "{{ inv_install_kibana__elastic_protocol }}"
        install_kibana__elastic_hosts: "{{ inv_install_kibana__elastic_hosts }}"
        install_kibana__elastic_client_auth: "{{ inv_install_kibana__elastic_client_auth }}"
        install_kibana__ssl_authorities: "{{ inv_install_kibana__ssl_authorities }}"
        install_kibana__ssl_key: "{{ inv_install_kibana__ssl_key }}"
        install_kibana__ssl_crt: "{{ inv_install_kibana__ssl_crt }}"
        install_kibana__elastic_ssl_authorities: "{{ inv_install_kibana__elastic_ssl_authorities }}"
        install_kibana__elastic_ssl_key: "{{ inv_install_kibana__elastic_ssl_key }}"
        install_kibana__elastic_ssl_crt: "{{ inv_install_kibana__elastic_ssl_crt }}"
      ansible.builtin.include_role:
        name: "labocbz.install_kibana"
