---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.install_kibana"
      tags:
        - "labocbz.install_kibana"
      vars:
        install_kibana_major_version: "{{ inv_install_kibana_major_version }}"
        install_kibana_config_path: "{{ inv_install_kibana_config_path }}"
        install_kibana_port: "{{ inv_install_kibana_port }}"
        install_kibana_cluster_name: "{{ inv_install_kibana_cluster_name }}"
        install_kibana_rewrite_base_path: "{{ inv_install_kibana_rewrite_base_path }}"
        install_kibana_base_path: "{{ inv_install_kibana_base_path }}"
        install_kibana_public_pase_url: "{{ inv_install_kibana_public_pase_url }}"
        install_kibana_ssl_src: "{{ inv_install_kibana_ssl_src }}"
        install_kibana_ssl_path: "{{ inv_install_kibana_ssl_path }}"
        install_kibana_elasticsearch_port: "{{ inv_install_kibana_elasticsearch_port }}"
        #install_kibana_service_account_token: "{{ inv_install_kibana_service_account_token }}"
        install_kibana_service_account_token_basename: "{{ inv_install_kibana_service_account_token_basename }}"
        install_kibana_elastic_password: "{{ inv_install_kibana_elastic_password }}"
        install_kibana_elastic_user: "{{ inv_install_kibana_elastic_user }}"
        install_kibana_elastic_protocol: "{{ inv_install_kibana_elastic_protocol }}"
        install_kibana_elastic_hosts: "{{ inv_install_kibana_elastic_hosts }}"
        install_kibana_elastic_client_auth: "{{ inv_install_kibana_elastic_client_auth }}"
        install_kibana_ssl_authorities: "{{ inv_install_kibana_ssl_authorities }}"
        install_kibana_ssl_key: "{{ inv_install_kibana_ssl_key }}"
        install_kibana_ssl_crt: "{{ inv_install_kibana_ssl_crt }}"
      ansible.builtin.include_role:
        name: "labocbz.install_kibana"
