---
# Don't forget to keep this file updated
# molecule/<scenario>/verify.yml
- name: "Verify"
  hosts: "all"
  gather_facts: false
  tasks:

    - name: "Get Kibana service current state"
      register: install_kibana_service_status
      failed_when: not install_kibana_service_status.status.ActiveState == 'active'
      ansible.builtin.systemd:
        name: "kibana"

    - name: "Check Kibana folders and conf"
      when: inv_install_kibana_ssl | default(false)
      loop:
        - "{{ inv_install_kibana_ssl_crt }}"
        - "{{ inv_install_kibana_ssl_key }}"
      loop_control:
        loop_var: folder_path
      register: folder_path
      failed_when: not folder_path.stat.exists
      ansible.builtin.stat:
        path: "{{ folder_path }}"

    - name: "Check Kibana connectivity"
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ inv_install_kibana_port }}"
        timeout: 240
